version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        Version: 1.0
    image: front:1.0
    container_name: front
    restart: always
    ports: 
      - 2024:80
networks:
  default:
    external:
      name: https